### ISSUE TITLE
コメントアウトがあったほうが読みやすいと思います

### ISSUE THREAD

**Issue by C0A21145** [c0a2113791/ProjExD#11]
https://github.com/c0a2113791/ProjExD/blob/3ffec58dbb090862077f96b5ce684dc8d5a92b2d/ex03/maze.py#L76

関数のところなどにコメントアウトがあったほうがどのような役割をしているかが分かりやすいと思います

**Comment by c0a2113791** [comment]
コメントアウト追加しました。
