### ISSUE TITLE
コードと同じ行にコメントアウトを入れるときは、tabキーである程度空白を入れた方が見やすくなると思います

### ISSUE THREAD

**Issue by MinamiSawamura** [c0a2113791/ProjExD#15]
https://github.com/c0a2113791/ProjExD/blob/2dcbe145297e9a0ca1dbb5c56144a04a90eacc83/ex04/dodge_bomb.py#L92

**Comment by c0a2113791** [comment]
ご指摘ありがとうございます。なおしました！
